name: build, lint and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci
  MAINNET_RPC_URL: ${{ vars.MAINNET_RPC_URL }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:optimized

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:optimized
